<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Dictionary[
  <!ELEMENT Dictionary (card)*>
  <!ELEMENT card (language)+>
  <!ELEMENT language (title?, subtitle?, description?, photogrammetry, computer_vision, robotics, external_links?, images?)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT subtitle (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT photogrammetry (#PCDATA | title)*>
  <!ELEMENT computer_vision (#PCDATA | title)*>
  <!ELEMENT robotics (#PCDATA | title)*>
  <!ELEMENT external_links (link)+>
  <!ELEMENT link (#PCDATA)>
  <!ELEMENT images (img)+>
  <!ELEMENT img (#PCDATA)>

  <!ATTLIST language
    country CDATA #REQUIRED>
  <!ATTLIST img
    pos CDATA #IMPLIED>
  ]>



<Dictionary>

  <card> <!-- Dictionary card, represents a single term -->
    <language country="IT">
      <!--  Italian content (IT)    -->
      <title>Overall card title (optional)</title>
      <subtitle>Overall subtitle (optional)</subtitle>
      <description>Overall description (optional)</description>
      <photogrammetry>
        <title>Title related to photogrammetry</title>
         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      </photogrammetry>
      <computer_vision>
        <title>Title related to computer vision</title>
        But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself,
      </computer_vision>
      <robotics>
        <title>Title related to robotics</title>
        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
      </robotics>
      <external_links>
        <link>Google.it</link> <!--   "lan" attribute stands for content language   (optional)  -->
        <link>www.lipsum.com/</link>
      </external_links>
      <images>
        <!--   "pos" specifies the order of the images (optional)     -->
        <img pos="0">NomeUnivoco.png</img>
        <img pos="1">Hello.png</img>
      </images>
    </language>

    <language country="EN">
      <!--  English content (EN)    -->
      <title>Overall card title (optional)</title>
      <subtitle>Overall subtitle (optional)</subtitle>
      <description>Overall description (optional)</description>
      <photogrammetry>
        <title>Title related to photogrammetry</title>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      </photogrammetry>
      <computer_vision>
        <title>Title related to computer vision</title>
        But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself,
      </computer_vision>
      <robotics>
        <title>Title related to robotics</title>
        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
      </robotics>
      <external_links>
        <link>Google.it</link> <!--   "lan" attribute stands for content language   (optional)  -->
        <link>www.lipsum.com/</link>
      </external_links>
      <images>
        <!--   "pos" specifies the order of the images (optional)     -->
        <img pos="0">ImageName.png</img>
        <img pos="1">Hello.png</img>
      </images>
    </language>
  </card>

  <!-- Add more cards below -->

</Dictionary>
